### ISSUE TITLE
/playerinfo NullPointerException

### ISSUE THREAD

**Issue by WouterG** [SpleefLeague/Core#15]
Getting the following error when doing "/pi ParaSyte_"

> [09:14:33 INFO]: Wouto1997 issued server command: /pi ParaSyte_
[09:14:33 WARN]: java.lang.NullPointerException
[09:14:33 WARN]:        at com.spleefleague.core.player.GeneralPlayer.getInventory(GeneralPlayer.java:662)
[09:14:33 WARN]:        at com.spleefleague.core.cosmetics.items.HeadHatItem.onSelecting(HeadHatItem.java:35)
[09:14:33 WARN]:        at com.spleefleague.core.cosmetics.Collectibles.lambda$apply$1(Collectibles.java:47)
[09:14:33 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[09:14:33 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[09:14:33 WARN]:        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
[09:14:33 WARN]:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[09:14:33 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[09:14:33 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[09:14:33 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[09:14:33 WARN]:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[09:14:33 WARN]:        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[09:14:33 WARN]:        at com.spleefleague.core.cosmetics.Collectibles.apply(Collectibles.java:47)
[09:14:33 WARN]:        at com.spleefleague.core.player.SLPlayer.done(SLPlayer.java:287)
[09:14:33 WARN]:        at com.spleefleague.core.io.EntityBuilder.deserialize(EntityBuilder.java:113)
[09:14:33 WARN]:        at com.spleefleague.core.io.EntityBuilder.load(EntityBuilder.java:94)
[09:14:33 WARN]:        at com.spleefleague.core.player.PlayerManager.load(PlayerManager.java:107)
[09:14:33 WARN]:        at com.spleefleague.core.player.PlayerManager.loadFake(PlayerManager.java:95)
[09:14:33 WARN]:        at com.spleefleague.core.command.commands.playerinfo.lambda$run$0(playerinfo.java:54)
[09:14:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[09:14:33 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[09:14:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[09:14:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[09:14:33 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by Jobarion** [comment]
Fixed
